blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Matrix
    url: https://matrix.to/#/#florisboard:matrix.org
    about: General chat about FlorisBoard and quick Q/A
  - name: â“ Questions / Feedback
    url: https://github.com/florisboard/florisboard/discussions/new/choose
    about: Post your questions or feedback in the discussions panel
